# fly.toml app configuration file generated for part13-myblogapp on 2025-05-15T17:07:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part13-myblogapp'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
